version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update -y
      - nvidia-smi
      - apt list --installed
      - apt-get install -y libgles2
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - node index.js
artifacts:
  files:
    - output.pdf