version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - nvidia-smi
      - apt list --installed
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - node index.js
artifacts:
  files:
    - output.pdf