version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update -y
      - apt-get install -y dbus libgles2
      - nvidia-smi
      - apt list --installed
  pre_build:
    commands:
      # - /etc/init.d/dbus start
      - dbus-run-session -- npm i
  build:
    commands:
      - node index.js
artifacts:
  files:
    - output.pdf